// src/integrations/supabase/client.ts

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnmmpumidejfwmrgsiun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZubW1wdW1pZGVqZndtcmdzaXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDk5MTAsImV4cCI6MjA3MjIyNTkxMH0.NmySt1VlKn8gdsPd8B4HkRJGMYegVpLyQeSsWpsFy_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Tempo de teste para expiração da sessão (em milissegundos)
// Para teste: 2 minutos = 2 * 60 * 1000 = 120000
// Para produção: comentar ou remover esta linha
export const TEST_SESSION_TIMEOUT = 2 * 60 * 1000; // 2 minutos

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});